# Generated by Django 3.2.5 on 2021-10-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to=True)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
