# Generated by Django 3.2.5 on 2021-10-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomeFiltersModelAdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='roles',
            field=models.CharField(blank=True, choices=[('1', 'Editor'), ('2', 'Author'), ('3', 'Admin')], max_length=200),
        ),
    ]
