# Generated by Django 3.2.5 on 2021-10-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelAdminHelpTextApp', '0002_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
